name             'cassandra'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cassandra'
long_description 'Installs/Configures cassandra'
version          '0.1.0'
